DROP TABLE OC_BOARD PURGE;
DROP TABLE OC_BOARD_RE PURGE;

DROP SEQUENCE BD_SQ;
DROP SEQUENCE BD_RE_SQ;

--게시판
CREATE SEQUENCE BD_SQ;
CREATE TABLE OC_BOARD(
NO NUMBER PRIMARY KEY, --seq
PNO NUMBER NULL REFERENCES OC_BOARD(NO), --부모
ID VARCHAR2(100) NOT NULL REFERENCES OC_MEMBER(ID), --글쓴사람
TITLE VARCHAR2(500) NOT NULL, --제목
CONTENT VARCHAR2(1000) NOT NULL, --내용
REGDATE DATE NOT NULL, --게시일
HIT NUMBER NOT NULL
);

--게시판 리플
CREATE SEQUENCE BD_RE_SQ;
CREATE TABLE OC_BOARD_RE(
NO NUMBER PRIMARY KEY, --seq 댓글 고유 번호
BNO NUMBER NOT NULL REFERENCES OC_BOARD(NO), --댓글이 속한 게시물 번호
PNO NUMBER NULL REFERENCES OC_BOARD_RE(NO), --상위댓글 번호 no
ID VARCHAR2(100) NOT NULL REFERENCES OC_MEMBER(ID), -- 글쓴사람
CONTENT VARCHAR2(300) NOT NULL, --내용
REGDATE DATE NOT NULL -- 댓글날짜
);



--테스트용
INSERT INTO OC_BOARD VALUES(BD_SQ.NEXTVAL, NULL, 'test1', 'test1', 'test1', SYSDATE, 0);
INSERT INTO OC_BOARD VALUES(BD_SQ.NEXTVAL, 1, 'test2', 'test2', 'test2', SYSDATE, 0);

INSERT INTO OC_BOARD_RE VALUES(BD_RE_SQ.NEXTVAL, 2, NULL, 'test2', 'test2', SYSDATE);
INSERT INTO OC_BOARD_RE VALUES(BD_RE_SQ.NEXTVAL, 2, 1, 'test2', 'test2', SYSDATE);






EMP
MGR == EMPNO












-----------------------------------------------------------------
--占쌉시뱄옙
SELECT *
FROM (SELECT ROWNUM AS RN, LPAD(NO, LEVEL*3, ' ') AS BNO, ID, TITLE, CONTENT, REGDATE
FROM AS_BOARD
START WITH PNO IS NULL
CONNECT BY PRIOR NO = PNO
ORDER SIBLINGS BY NO DESC);
WHERE RN = 2;


INSERT INTO OC_BOARD VALUES(BD_SQ.NEXTVAL, NULL, 'TEST1', 'TEST1', 'TEST1', SYSDATE);
INSERT INTO OC_BOARD VALUES(BD_SQ.NEXTVAL, NULL, 'TEST2', 'TEST2', 'TEST2', SYSDATE);
INSERT INTO OC_BOARD VALUES(BD_SQ.NEXTVAL, NULL, 'TEST3', 'TEST3', 'TEST3', SYSDATE);

INSERT INTO OC_BOARD VALUES(BD_SQ.NEXTVAL, 1, 'TEST3', 'TEST3', 'TEST3', SYSDATE);
INSERT INTO OC_BOARD VALUES(BD_SQ.NEXTVAL, 4, 'TEST2', 'TEST2', 'TEST2', SYSDATE);
INSERT INTO OC_BOARD VALUES(BD_SQ.NEXTVAL, 1, 'TEST3', 'TEST3', 'TEST3', SYSDATE);
INSERT INTO OC_BOARD VALUES(BD_SQ.NEXTVAL, 6, 'TEST1', 'TEST1', 'TEST1', SYSDATE);


--占쏙옙占�
SELECT LPAD(NO, LEVEL*3, ' ') AS NO, PNO, ID, CONTENT, REGDATE
FROM AS_BOARD_RE
START WITH PNO IS NULL
CONNECT BY PRIOR NO = PNO;


