DROP TABLE OC_REVIEW PURGE;
DROP SEQUENCE OC_REVIEW_SQ;

CREATE SEQUENCE OC_REVIEW_SQ;

CREATE TABLE OC_REVIEW(
NO NUMBER PRIMARY KEY,
SPANAME VARCHAR2(50) NOT NULL,
ID VARCHAR2(100) NOT NULL REFERENCES OC_MEMBER(ID),
CONTENT VARCHAR2(200) NOT NULL,
STAR NUMBER NOT NULL,
REGDATE VARCHAR2(10) NOT NULL,
CONSTRAINT STAR_CHK CHECK(STAR BETWEEN 1 AND 5)
);

INSERT INTO OC_REVIEW VALUES(OC_REVIEW_SQ.NEXTVAL, '이천(미란다,설봉)', 'test1', '좋아용', 5, TO_CHAR(SYSDATE, 'YYYY.MM.DD'));
INSERT INTO OC_REVIEW VALUES(OC_REVIEW_SQ.NEXTVAL, '이천(미란다,설봉)', 'test2', '뀨 별루', 5, TO_CHAR(SYSDATE, 'YYYY.MM.DD'));
INSERT INTO OC_REVIEW VALUES(OC_REVIEW_SQ.NEXTVAL, '이천(미란다,설봉)', 'test1', '그닥', 5, TO_CHAR(SYSDATE, 'YYYY.MM.DD'));
INSERT INTO OC_REVIEW VALUES(OC_REVIEW_SQ.NEXTVAL, '이천(미란다,설봉)', 'test4', '흠', 3, TO_CHAR(SYSDATE, 'YYYY.MM.DD'));
INSERT INTO OC_REVIEW VALUES(OC_REVIEW_SQ.NEXTVAL, '이천(미란다,설봉)', 'test5', '우', 2, TO_CHAR(SYSDATE, 'YYYY.MM.DD'));

INSERT INTO OC_REVIEW VALUES(OC_REVIEW_SQ.NEXTVAL, '이천(미란다,설봉)', 'test10', '테스트', 1, TO_CHAR(SYSDATE, 'YYYY.MM.DD'));

SELECT OC_REVIEW.NO, SPANAME, ID, CONTENT, STAR, REGDATE, FACE
FROM OC_REVIEW  INNER JOIN OC_MEMBER
USING (ID)
WHERE SPANAME='이천(미란다,설봉)'
ORDER BY 1 DESC
